install-dir = "./build"
link-target = "~/.local/bin/qtile"
# X not yet supported
backend = "wayland"

faulthandler = true

[venv]
dir = ".venv"
args = "-p python3.10"

[extensions]

[extensions.extras]
repo = "https://github.com/elParaguayo/qtile-extras"
dependencies = ["psutil", "iwlib", "pyxdg"]
